[package]
name = "ac-platform-win"
version = "0.1.0"
edition = "2021"

[lib]
name = "ac_platform_win"
path = "src/lib.rs"

[[bin]]
name = "autocorrect"
path = "src/main.rs"

[dependencies]
ac-core = { path = "../ac-core" }
ac-config = { path = "../ac-config" }
ac-telex = { path = "../ac-telex" }

[dependencies.windows]
version = "0.61"
features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_Security",
  "Win32_System_Com",
  "Win32_System_Console",
  "Win32_System_LibraryLoader",
  "Win32_System_Ole",
  "Win32_System_Performance",
  "Win32_System_Registry",
  "Win32_System_SystemInformation",
  "Win32_System_Threading",
  "Win32_System_Variant",
  "Win32_UI_Accessibility",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
]
